<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>io.github.aresxue.boot</groupId>
    <artifactId>ares-boot-starter</artifactId>
    <version>1.1.3-SNAPSHOT</version>
  </parent>

  <artifactId>ares-boot-starter-timed-job-adapter</artifactId>
  <name>Ares Boot Starter Timed Job Adapter</name>
  <packaging>pom</packaging>
  <description>
    定时任务快速使用，可自动从配置中心获取定时任务服务器信息，提供注解方式进行分布式任务调度，提供任务执行前后的拦截器机制，
    基于base集成全链路信息（包括tid）跨线程跨线程池跨进程传递的功能
    Task use quickly, can automatically obtain scheduled task server information from
    the configuration center, and provide annotations for distributed task scheduling.
    Provide interceptor mechanisms before and after task execution,
    base - based integration full link information (including tid) across thread, across thread pool
    and across process transmission function
  </description>
  <url>https://github.com/Aresxue/ares-parent</url>

  <licenses>
    <license>
      <name>The Apache Software License, Version 2.0</name>
      <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
    </license>
  </licenses>

  <scm>
    <connection>scm:git@github.com:Aresxue/ares-parent.git</connection>
    <developerConnection>scm:git@github.com:Aresxue/ares-parent.git</developerConnection>
    <url>https://github.com/Aresxue/ares-parent</url>
  </scm>

  <developers>
    <developer>
      <id>ares</id>
      <name>Ares Xue</name>
      <email>ares320635@gmail.com</email>
      <organization>https://github.com/Aresxue</organization>
      <roles>
        <role>Java Development Engineer</role>
      </roles>
      <timezone>+8</timezone>
    </developer>
  </developers>


  <modules>
    <module>ares-boot-starter-timed-job-api</module>
    <module>ares-boot-starter-timed-job-abstract</module>
    <module>ares-boot-starter-timed-job</module>
    <module>ares-boot-starter-timed-job-schedulerx2</module>
  </modules>

</project>