<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>io.github.aresxue.boot.util</groupId>
    <artifactId>ares-boot-util</artifactId>
    <version>1.1.3-SNAPSHOT</version>
  </parent>

  <artifactId>ares-boot-util-ognl</artifactId>
  <name>Ares Boot Util Ognl</name>
  <description>
    提供ognl表达式解析
    Provides ognl expression parsing
  </description>
  <url>https://github.com/Aresxue/ares-parent</url>

  <licenses>
    <license>
      <name>The Apache Software License, Version 2.0</name>
      <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
    </license>
  </licenses>

  <scm>
    <connection>scm:git@github.com:Aresxue/ares-parent.git</connection>
    <developerConnection>scm:git@github.com:Aresxue/ares-parent.git</developerConnection>
    <url>https://github.com/Aresxue/ares-parent</url>
  </scm>

  <developers>
    <developer>
      <id>ares</id>
      <name>Ares Xue</name>
      <email>ares320635@gmail.com</email>
      <organization>https://github.com/Aresxue</organization>
      <roles>
        <role>Java Development Engineer</role>
      </roles>
      <timezone>+8</timezone>
    </developer>
  </developers>


  <dependencies>
    <dependency>
      <groupId>io.github.aresxue.boot.util</groupId>
      <artifactId>ares-boot-util-test</artifactId>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>ognl</groupId>
      <artifactId>ognl</artifactId>
    </dependency>
  </dependencies>

</project>