ares:
  application:
    name: ares-boot-demo
  web:
    doc:
      enabled: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %c#%M#%L: %msg%xEx%n"

mybatis-plus:
  type-aliases-package: cn.ares.boot.demo

spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/ares_boot_demo
      username: ares
      password: 123456

springdoc:
  group-configs:
    - group: '应用接口文档'
      paths-to-match: '/**'
      packages-to-scan: cn.ares.boot.demo


