<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>io.github.aresxue.boot</groupId>
    <artifactId>ares-boot-dependency</artifactId>
    <version>1.1.1-RC</version>
  </parent>

  <artifactId>ares-boot-util-dependency-management</artifactId>
  <name>Ares Boot Util Dependency Management</name>
  <packaging>pom</packaging>
  <description>
    管理所有util模块的依赖
    Manage dependencies of all ares-boot-util modules
  </description>
  <url>https://github.com/Aresxue/ares-parent</url>

  <licenses>
    <license>
      <name>The Apache Software License, Version 2.0</name>
      <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
    </license>
  </licenses>

  <scm>
    <connection>scm:git@github.com:Aresxue/ares-parent.git</connection>
    <developerConnection>scm:git@github.com:Aresxue/ares-parent.git</developerConnection>
    <url>https://github.com/Aresxue/ares-parent</url>
  </scm>

  <developers>
    <developer>
      <id>ares</id>
      <name>Ares Xue</name>
      <email>ares320635@gmail.com</email>
      <organization>https://github.com/Aresxue</organization>
      <roles>
        <role>Java Development Engineer</role>
      </roles>
      <timezone>+8</timezone>
    </developer>
  </developers>


  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.github.aresxue.boot.util</groupId>
        <artifactId>ares-boot-util-common</artifactId>
        <version>${boot.version}</version>
      </dependency>

      <dependency>
        <groupId>io.github.aresxue.boot.util</groupId>
        <artifactId>ares-boot-util-crypt</artifactId>
        <version>${boot.version}</version>
      </dependency>

      <dependency>
        <groupId>io.github.aresxue.boot.util</groupId>
        <artifactId>ares-boot-util-http</artifactId>
        <version>${boot.version}</version>
      </dependency>

      <dependency>
        <groupId>io.github.aresxue.boot.util</groupId>
        <artifactId>ares-boot-util-json</artifactId>
        <version>${boot.version}</version>
      </dependency>

      <dependency>
        <groupId>io.github.aresxue.boot.util</groupId>
        <artifactId>ares-boot-util-mapstruct</artifactId>
        <version>${boot.version}</version>
      </dependency>

      <dependency>
        <groupId>io.github.aresxue.boot.util</groupId>
        <artifactId>ares-boot-util-ognl</artifactId>
        <version>${boot.version}</version>
      </dependency>

      <dependency>
        <groupId>io.github.aresxue.boot.util</groupId>
        <artifactId>ares-boot-util-servlet</artifactId>
        <version>${boot.version}</version>
      </dependency>

      <dependency>
        <groupId>io.github.aresxue.boot.util</groupId>
        <artifactId>ares-boot-util-spring</artifactId>
        <version>${boot.version}</version>
      </dependency>

      <dependency>
        <groupId>io.github.aresxue.boot.util</groupId>
        <artifactId>ares-boot-util-test</artifactId>
        <version>${boot.version}</version>
      </dependency>

      <dependency>
        <groupId>io.github.aresxue.boot.util</groupId>
        <artifactId>ares-boot-util-yaml</artifactId>
        <version>${boot.version}</version>
      </dependency>

      <dependency>
        <groupId>io.github.aresxue.boot.util</groupId>
        <artifactId>ares-boot-util-log</artifactId>
        <version>${boot.version}</version>
      </dependency>

      <dependency>
        <groupId>io.github.aresxue.boot.util</groupId>
        <artifactId>ares-boot-util-compress</artifactId>
        <version>${boot.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

</project>