<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>io.github.aresxue.boot</groupId>
    <artifactId>ares-boot-dependency</artifactId>
    <version>1.1.2-RC1</version>
  </parent>

  <artifactId>business-api-required</artifactId>
  <name>Business Api Required</name>
  <description>
    集成所有业务api模块需要的依赖
    Integrated all required dependencies of business api module
  </description>
  <url>https://github.com/Aresxue/ares-parent</url>

  <licenses>
    <license>
      <name>The Apache Software License, Version 2.0</name>
      <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
    </license>
  </licenses>

  <scm>
    <connection>scm:git@github.com:Aresxue/ares-parent.git</connection>
    <developerConnection>scm:git@github.com:Aresxue/ares-parent.git</developerConnection>
    <url>https://github.com/Aresxue/ares-parent</url>
  </scm>

  <developers>
    <developer>
      <id>ares</id>
      <name>Ares Xue</name>
      <email>ares320635@gmail.com</email>
      <organization>https://github.com/Aresxue</organization>
      <roles>
        <role>Java Development Engineer</role>
      </roles>
      <timezone>+8</timezone>
    </developer>
  </developers>



  <dependencies>
    <dependency>
      <groupId>io.github.aresxue.boot</groupId>
      <artifactId>ares-boot-base-model</artifactId>
    </dependency>
    <dependency>
      <groupId>io.github.aresxue.boot</groupId>
      <artifactId>ares-boot-base-validation</artifactId>
    </dependency>

    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
    </dependency>

    <dependency>
      <groupId>io.swagger.core.v3</groupId>
      <artifactId>swagger-annotations</artifactId>
    </dependency>
  </dependencies>


  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.github.aresxue.boot</groupId>
        <artifactId>ares-boot-base-dependency-management</artifactId>
        <version>${boot.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>io.github.aresxue.boot</groupId>
        <artifactId>third-dependency-management</artifactId>
        <version>${boot.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

</project>