<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>io.github.aresxue.boot</groupId>
    <artifactId>ares-boot-dependency</artifactId>
    <version>1.1.2</version>
  </parent>

  <artifactId>ares-boot-starter-dependency-management</artifactId>
  <name>Ares Boot Starter Dependency Management</name>
  <packaging>pom</packaging>
  <description>
    管理所有starter模块的依赖
    Manage dependencies of all ares-boot-starter modules
  </description>
  <url>https://github.com/Aresxue/ares-parent</url>

  <licenses>
    <license>
      <name>The Apache Software License, Version 2.0</name>
      <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
    </license>
  </licenses>

  <scm>
    <connection>scm:git@github.com:Aresxue/ares-parent.git</connection>
    <developerConnection>scm:git@github.com:Aresxue/ares-parent.git</developerConnection>
    <url>https://github.com/Aresxue/ares-parent</url>
  </scm>

  <developers>
    <developer>
      <id>ares</id>
      <name>Ares Xue</name>
      <email>ares320635@gmail.com</email>
      <organization>https://github.com/Aresxue</organization>
      <roles>
        <role>Java Development Engineer</role>
      </roles>
      <timezone>+8</timezone>
    </developer>
  </developers>


  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.github.aresxue.boot</groupId>
        <artifactId>ares-boot-starter-cache-related</artifactId>
        <version>${boot.version}</version>
      </dependency>
      <dependency>
        <groupId>io.github.aresxue.boot</groupId>
        <artifactId>ares-boot-starter-cache-api</artifactId>
        <version>${boot.version}</version>
      </dependency>
      <dependency>
        <groupId>io.github.aresxue.boot</groupId>
        <artifactId>ares-boot-starter-cache</artifactId>
        <version>${boot.version}</version>
      </dependency>
      <dependency>
        <groupId>io.github.aresxue.boot</groupId>
        <artifactId>ares-boot-starter-dynamic-cache</artifactId>
        <version>${boot.version}</version>
      </dependency>

      <dependency>
        <groupId>io.github.aresxue.boot</groupId>
        <artifactId>ares-boot-starter-config</artifactId>
        <version>${boot.version}</version>
      </dependency>

      <dependency>
        <groupId>io.github.aresxue.boot</groupId>
        <artifactId>ares-boot-starter-datasource-related</artifactId>
        <version>${boot.version}</version>
      </dependency>
      <dependency>
        <groupId>io.github.aresxue.boot</groupId>
        <artifactId>ares-boot-starter-datasource</artifactId>
        <version>${boot.version}</version>
      </dependency>
      <dependency>
        <groupId>io.github.aresxue.boot</groupId>
        <artifactId>ares-boot-starter-datasource-sharding</artifactId>
        <version>${boot.version}</version>
      </dependency>
      <dependency>
        <groupId>io.github.aresxue.boot</groupId>
        <artifactId>ares-boot-starter-dynamic-datasource</artifactId>
        <version>${boot.version}</version>
      </dependency>

      <dependency>
        <groupId>io.github.aresxue.boot</groupId>
        <artifactId>ares-boot-starter-file-storage</artifactId>
        <version>${boot.version}</version>
      </dependency>

      <dependency>
        <groupId>io.github.aresxue.boot</groupId>
        <artifactId>ares-boot-starter-mq-adapter</artifactId>
        <version>${boot.version}</version>
      </dependency>
      <dependency>
        <groupId>io.github.aresxue.boot</groupId>
        <artifactId>ares-boot-starter-mq-api</artifactId>
        <version>${boot.version}</version>
      </dependency>
      <dependency>
        <groupId>io.github.aresxue.boot</groupId>
        <artifactId>ares-boot-starter-mq-abstract</artifactId>
        <version>${boot.version}</version>
      </dependency>
      <dependency>
        <groupId>io.github.aresxue.boot</groupId>
        <artifactId>ares-boot-starter-mq</artifactId>
        <version>${boot.version}</version>
      </dependency>

      <dependency>
        <groupId>io.github.aresxue.boot</groupId>
        <artifactId>ares-boot-starter-rpc-adapter</artifactId>
        <version>${boot.version}</version>
      </dependency>
      <dependency>
        <groupId>io.github.aresxue.boot</groupId>
        <artifactId>ares-boot-starter-rpc-api</artifactId>
        <version>${boot.version}</version>
      </dependency>
      <dependency>
        <groupId>io.github.aresxue.boot</groupId>
        <artifactId>ares-boot-starter-rpc-abstract</artifactId>
        <version>${boot.version}</version>
      </dependency>
      <dependency>
        <groupId>io.github.aresxue.boot</groupId>
        <artifactId>ares-boot-starter-rpc</artifactId>
        <version>${boot.version}</version>
      </dependency>

      <dependency>
        <groupId>io.github.aresxue.boot</groupId>
        <artifactId>ares-boot-starter-rule-engine</artifactId>
        <version>${boot.version}</version>
      </dependency>

      <dependency>
        <groupId>io.github.aresxue.boot</groupId>
        <artifactId>ares-boot-starter-search-engine</artifactId>
        <version>${boot.version}</version>
      </dependency>

      <dependency>
        <groupId>io.github.aresxue.boot</groupId>
        <artifactId>ares-boot-starter-spring</artifactId>
        <version>${boot.version}</version>
      </dependency>

      <dependency>
        <groupId>io.github.aresxue.boot</groupId>
        <artifactId>ares-boot-starter-timed-job-adapter</artifactId>
        <version>${boot.version}</version>
      </dependency>
      <dependency>
        <groupId>io.github.aresxue.boot</groupId>
        <artifactId>ares-boot-starter-timed-job-api</artifactId>
        <version>${boot.version}</version>
      </dependency>
      <dependency>
        <groupId>io.github.aresxue.boot</groupId>
        <artifactId>ares-boot-starter-timed-job-abstract</artifactId>
        <version>${boot.version}</version>
      </dependency>
      <dependency>
        <groupId>io.github.aresxue.boot</groupId>
        <artifactId>ares-boot-starter-timed-job</artifactId>
        <version>${boot.version}</version>
      </dependency>
      <dependency>
        <groupId>io.github.aresxue.boot</groupId>
        <artifactId>ares-boot-starter-timed-job-schedulerx2</artifactId>
        <version>${boot.version}</version>
      </dependency>

      <dependency>
        <groupId>io.github.aresxue.boot</groupId>
        <artifactId>ares-boot-starter-test</artifactId>
        <version>${boot.version}</version>
      </dependency>

      <dependency>
        <groupId>io.github.aresxue.boot</groupId>
        <artifactId>ares-boot-starter-validation</artifactId>
        <version>${boot.version}</version>
      </dependency>

      <dependency>
        <groupId>io.github.aresxue.boot</groupId>
        <artifactId>ares-boot-starter-web</artifactId>
        <version>${boot.version}</version>
      </dependency>

      <dependency>
        <groupId>io.github.aresxue.boot</groupId>
        <artifactId>ares-boot-starter-workflow</artifactId>
        <version>${boot.version}</version>
      </dependency>

    </dependencies>
  </dependencyManagement>

</project>